# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Pgyer Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    pgyer(api_key: "56e6639ddf4add46100ecc0092eabb79", user_key: "4ab0636fc32b12eadae456e9c7d1721c", password: "123456", install_type: "2")
  end
end
